export default [
  { initials: "AN", name: "ANDAMAN & NICOBAR ISLANDS", count: 190 },
  { initials: "AP", name: "ANDHRA PRADESH", count: 7339 },
  { initials: "AR", name: "ARUNACHAL PRADESH", count: 596 },
  { initials: "AS", name: "ASSAM", count: 3267 },
  { initials: "BI", name: "BIHAR", count: 7064 },
  { initials: "CH", name: "CHANDIGARH", count: 302 },
  { initials: "CG", name: "CHHATTISGARH", count: 2622 },
  { initials: "DN", name: "DADRA & NAGAR HAVELI", count: 43 },
  { initials: "DD", name: "DAMAN & DIU", count: 25 },
  { initials: "DL", name: "DELHI", count: 15332 },
  { initials: "GA", name: "GOA", count: 378 },
  { initials: "GJ", name: "GUJARAT", count: 9841 },
  { initials: "HR", name: "HARYANA", count: 5611 },
  { initials: "HP", name: "HIMACHAL PRADESH", count: 1089 },
  { initials: "JK", name: "JAMMU & KASHMIR", count: 2143 },
  { initials: "JH", name: "JHARKHAND", count: 3670 },
  { initials: "KA", name: "KARNATAKA", count: 11864 },
  { initials: "KL", name: "KERALA", count: 5860 },
  { initials: "LD", name: "LADAKH", count: 206 },
  { initials: "LD", name: "LAKSHADWEEP", count: 9 },
  { initials: "MP", name: "MADHYA PRADESH", count: 9058 },
  { initials: "MH", name: "MAHARASHTRA", count: 28141 },
  { initials: "MN", name: "MANIPUR", count: 2914 },
  { initials: "ML", name: "MEGHALAYA", count: 394 },
  { initials: "MZ", name: "MIZORAM", count: 312 },
  { initials: "NL", name: "NAGALAND", count: 554 },
  { initials: "OD", name: "ORISSA", count: 5570 },
  { initials: "PY", name: "PUDUCHERRY", count: 386 },
  { initials: "PB", name: "PUNJAB", count: 2997 },
  { initials: "RJ", name: "RAJASTHAN", count: 8450 },
  { initials: "SK", name: "SIKKIM", count: 171 },
  { initials: "TN", name: "TAMIL NADU", count: 13973 },
  { initials: "TS", name: "TELANGANA", count: 5606 },
  { initials: "TR", name: "TRIPURA", count: 613 },
  { initials: "UP", name: "UTTAR PRADESH", count: 29597 },
  { initials: "UK", name: "UTTARAKHAND", count: 2897 },
  { initials: "WB", name: "WEST BENGAL", count: 14857 },
];
